# CÍL 4: NumPy

> Tento notebook je součástí cvičení 12 předmětu BPC-PRG.  
> Projdi ho postupně – každou buňku spusť klávesou **Shift+Enter**.  
> 📥 **[Stáhnout notebook (cviceni_12_numpy.ipynb)](cviceni_12_numpy.ipynb)** &nbsp;|&nbsp; 📥 **[Stáhnout data (pacienti.npy)](../pacienti.npy)**
>
> Data potřebuješ pro závěrečný úkol — stáhni si `pacienti.npy` vedle notebooku.


## Co je NumPy?

[**NumPy**](https://numpy.org/) *(Numerical Python)* je open-source matematická knihovna jazyka Python, na které stojí celý vědecký Python ekosystém. Vznikla v roce 2005 a dnes ji využívají datové vědy, fyzika, bioinformatika i strojové učení.

Jejím jádrem je datová struktura **`ndarray`** (N-dimensional array) – kompaktní pole čísel uložené přímo v paměti jako v jazyku C. Na rozdíl od Python listu ukládá všechny prvky stejného datového typu bez doprovodných objektů a metadat a operace nad ním jsou implementovány v kompilovaném C/Fortran kódu.

> **Tip:** NumPy v Pythonu z velké části nahrazuje MATLAB – syntaxe je velmi podobná, ale Python je volně dostupný a aktivně vyvíjený.

### Kde NumPy potkáš v biomedicíně?

| Oblast                                  | Popis                                                     |
|-----------------------------------------|-----------------------------------------------------------|
| Zpracování signálů (EKG, EEG, SpO₂)     | Časové řady jako 1D pole, FFT, filtrování                 |
| Medicínské snímky (MRI, CT, histologie) | 2D/3D matice pixelů, geometrické transformace             |
| Klinická data a biostatistika           | Rychlé výpočty průměrů, std, korelací na tisících záznamů |
| Strojové učení a AI                     | Všechny datové sady jsou interně numpy pole               |

### Místo v Python ekosystému

NumPy je základ, na kterém staví ostatní vědecké knihovny:

```
NumPy ──► Matplotlib   (grafy, vizualizace)
      ──► Pandas       (tabulková data, DataFrame)
      ──► SciPy        (vědecké algoritmy – FFT, filtry, statistická analýza)
      ──► scikit-learn (strojové učení)
      ──► TensorFlow / PyTorch  (hluboké neuronové sítě)
```

Standardní import – zkratka `np` je všeobecnou konvencí:

```python
import numpy as np
```

## 2.1 Proč numpy a ne Python seznam?

**numpy pole (`ndarray`)** je základní datová struktura knihovny NumPy. Na rozdíl od Python listu:

- uchovává data v **kompaktním bloku paměti stejného datového typu** (např. všechna `float64`),
- operace jsou implementované v C/Fortran – Python smyčka není potřeba,
- mohou být **vícerozměrná** (2D matice, 3D tenzory…),
- podporují přímou **matematickou syntaxi**: `a * 2`, `a + b`, `np.sin(a)` – bez `for` cyklu.

Výsledek: **10–100× rychlejší** pro numerické operace a výrazně čitelnější kód.

Srovnání syntaxe – násobení každého prvku dvěma:

```python
# Python list – musíš projít každý prvek
result = [x * 2 for x in my_list]

# NumPy – přímá matematická operace na celém poli
result = my_array * 2
```

In [3]:
import numpy as np
import time

n = 10_000_000
py_list  = list(range(n))
np_array = np.arange(n)

# Varianta 1 – klasická for smyčka
result_loop = [0] * n
start = time.time()
for i in range(n):
    result_loop[i] = py_list[i] * 2
t_loop = time.time() - start

# Varianta 2 – list comprehension
start = time.time()
result_lc = [x * 2 for x in py_list]
t_lc = time.time() - start

# Varianta 3 – NumPy vektorizace
start = time.time()
result_np = np_array * 2
t_np = time.time() - start

print(f"for smyčka:         {t_loop:.3f} s")
print(f"list comprehension: {t_lc:.3f} s")
print(f"NumPy:              {t_np:.3f} s")
print(f"\nNumPy vs for smyčka:        {t_loop / t_np:.0f}×")
print(f"NumPy vs list comprehension: {t_lc / t_np:.0f}×")


for smyčka:         22.778 s
list comprehension: 15.136 s
NumPy:              4.231 s

NumPy vs for smyčka:        5×
NumPy vs list comprehension: 4×


## 2.2 Vytvoření pole

In [1]:
import numpy as np

# Ze seznamu
a = np.array([1, 2, 3, 4, 5])
a


array([1, 2, 3, 4, 5])

In [ ]:
# Číselná řada – arange(start, stop, krok)
np.arange(0, 10, 2)


In [ ]:
# Rovnoměrně rozložené hodnoty – ideální pro časové osy
np.linspace(0, 1, 6)   # 6 hodnot od 0 do 1 včetně


In [ ]:
np.zeros(4)


In [ ]:
np.ones((2, 3))


In [ ]:
# Gaussův šum – realistické biomedicínské hodnoty
noise = np.random.normal(loc=0, scale=0.1, size=8)
np.round(noise, 3)


## 2.3 Tvar, datové typy a reshape

### Tvar a indexování – 1D pole

In [2]:
signal = np.array([0.5, 1.2, 1.8, 0.9, 2.1, 1.5, 0.7, 1.1])
signal


array([0.5, 1.2, 1.8, 0.9, 2.1, 1.5, 0.7, 1.1])

In [ ]:
signal.shape, signal.ndim, len(signal)


In [ ]:
signal[0], signal[-1]   # první a poslední prvek


In [ ]:
signal[2:5]   # prvky od indexu 2 po index 4


In [ ]:
signal[::2]   # každý druhý prvek


### 2D pole (matice)

In [6]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
matrix.shape


(3, 3)

In [8]:
matrix[1, 2]   # druhý řádek, třetí sloupec → 6


np.int64(6)

In [9]:
matrix[0, :]   # první řádek


array([1, 2, 3])

In [10]:
matrix[:, 1]   # druhý sloupec


array([2, 5, 8])

### Datové typy (dtype)

In [ ]:
a_int = np.array([1, 2, 3])
a_int.dtype


In [ ]:
a_float = np.array([1.0, 2.0, 3.0])
a_float.dtype


In [ ]:
# Explicitní nastavení – float32 ušetří paměť oproti float64
a32 = np.zeros(4, dtype=np.float32)
print(f"dtype: {a32.dtype}   paměť na prvek: {a32.itemsize} B")


In [ ]:
# Konverze dtype pomocí astype
a_int.astype(float)


### Změna tvaru (reshape)

In [ ]:
flat = np.arange(12)
flat


In [ ]:
flat.reshape(3, 4)   # 3 řádky × 4 sloupce


In [ ]:
flat.reshape(2, 2, 3).shape   # 3D tenzor


In [ ]:
# -1 = NumPy dopočítá rozměr automaticky
flat.reshape(1, -1).shape, flat.reshape(-1, 1).shape


## 2.4 Pokročilé indexování

Kromě klasického slicingu nabízí NumPy dva mocné způsoby výběru prvků:

- **Fancy indexing** – výběr pomocí pole celých čísel (libovolné pozice),
- **Boolean (binární) indexing** – výběr pomocí masky True/False (filtrování dle podmínky).

### Fancy indexing

In [13]:
data = np.array([10, 20, 30, 40, 50, 60, 70, 80])
data[[0, 2, 5]]   # prvky na pozicích 0, 2, 5


array([10, 30, 60])

In [14]:
data[[5, 0, 5, 2]]   # libovolné pořadí, opakování je OK


array([60, 10, 60, 30])

In [15]:
# Výběr konkrétních pacientů z matice měření
mereni = np.array([[120, 80, 72],   # pacient 0: systola, diastola, TF
                   [135, 88, 90],   # pacient 1
                   [118, 76, 65],   # pacient 2
                   [145, 95, 88]])  # pacient 3

mereni[[0, 2]]   # pacienti 0 a 2


array([[120,  80,  72],
       [118,  76,  65]])

### Boolean (binární) indexing

In [16]:
# Maska – pole True/False stejné délky jako data
mask = np.array([True, False, True, False, True, False, True, False])
data[mask]


array([10, 30, 50, 70])

In [18]:
# Masku nejčastěji vytvoříme podmínkou přímo
data > 40


array([False, False, False, False,  True,  True,  True,  True])

In [17]:
data[data > 40]


array([50, 60, 70, 80])

In [19]:
# Kombinace podmínek: & = AND,  | = OR
data[(data > 20) & (data < 70)]


array([30, 40, 50, 60])

In [20]:
# Detekce R-peaků: indexy vzorků nad prahem 1.0
ekg = np.array([0.1, 0.3, 1.4, 1.6, 0.5, 0.2, 1.5, 0.3])
np.where(ekg > 1.0)[0]


array([2, 3, 6])

## 2.5 Matematické operace

NumPy operace jsou **vektorizované** – pracují na celém poli naráz, bez explicitního cyklu.

In [21]:
a = np.array([1.0, 2.0, 3.0, 4.0])
b = np.array([0.5, 0.5, 0.5, 0.5])

a + b


array([1.5, 2.5, 3.5, 4.5])

In [22]:
a ** 2


array([ 1.,  4.,  9., 16.])

In [23]:
np.round(np.sqrt(a), 3)


array([1.   , 1.414, 1.732, 2.   ])

In [24]:
print(f"sum: {a.sum()}   mean: {a.mean()}   std: {a.std():.3f}")
print(f"min: {a.min()}   max: {a.max()}")


sum: 10.0   mean: 2.5   std: 1.118
min: 1.0   max: 4.0


In [25]:
# Podmínkové indexování a agregace v jednom výrazu
a[a > 2].mean()


np.float64(3.5)

## 2.6 Ukládání a načítání polí

NumPy má vlastní binární formáty, které zachovají dtype a tvar přesně:

| Formát | Funkce | Obsah |
|--------|--------|-------|
| `.npy` | `np.save` / `np.load` | jedno pole |
| `.npz` | `np.savez` / `np.load` | více pojmenovaných polí v jednom souboru |

```python
# .npy – jedno pole
np.save('data.npy', pole)       # uložit
pole = np.load('data.npy')      # načíst → přímo ndarray

# .npz – více polí najednou
np.savez('data.npz', x=cas, y=signal, meta=pole3)  # uložit
d = np.load('data.npz')                             # načíst → dict-like objekt
cas, signal = d['x'], d['y']                        # přístup přes klíče
```

> **Tip:** `.npz` se hodí, když potřebuješ předat více polí dohromady – například v dalším cíli uložíme takto všechna data pro Matplotlib (EKG, MRI, glykémie…) do jednoho souboru `mpl_data.npz`.

---

### ÚKOL: Analýza dat klinické studie

Stáhni si datový soubor se záznamy 20 pacientů:  
📥 **[pacienti.npy](../pacienti.npy)**

Soubor obsahuje 2D pole tvaru `(20, 3)` – každý řádek je jeden pacient, sloupce jsou:
| Sloupec | Ukazatel | Jednotka |
|---------|----------|----------|
| 0 | Systolický krevní tlak | mmHg |
| 1 | Diastolický krevní tlak | mmHg |
| 2 | Tepová frekvence | BPM |

Formát `.npy` je binární formát NumPy – rychlý a přesný (zachovává dtype, tvar). Načteš ho jednoduše:
```python
data = np.load("pacienti.npy")
```

**1.** Načti soubor `pacienti.npy` a vypiš tvar pole a prvních 5 řádků.

**2.** Vypiš průměr a směrodatnou odchylku každého ukazatele.

**3.** Pomocí boolean indexingu najdi pacienty s hypertenzí – systolický tlak ≥ 140 mmHg. Vypiš jejich počet a průměrný systolický tlak.

**4.** Přidej 4. sloupec: **pulzní tlak** = systolický − diastolický. Použij `np.column_stack()` nebo `np.hstack()`.

**5.** Zjisti, který pacient má nejvyšší tepovou frekvenci – vypiš jeho index a celý záznam. Použij `np.argmax()`.


In [30]:
import numpy as np

# 1. Načtení dat
data = np.load("pacienti.npy")
print(data)

# 2. Průměr a std každého ukazatele
print("Priemer:", data.mean(axis=0))
print("Smerodajná odchýlka:", data.std(axis=0))

# 3. Pacienti s hypertenzí (systolický ≥ 140)
hyper = data[data[:, 0] >= 140]
print("Počet pacientov s hypertenziou:", hyper.shape[0])
print("Priemerný systolický tlak:", hyper[:, 0].mean())


# 4. Pulzní tlak jako nový sloupec
pulse = data[:, 0] - data[:, 1]
data = np.column_stack((data, pulse))
print("Dáta s pulzným tlakom:\n", data)

# 5. Pacient s nejvyšší tepovou frekvencí
idx = np.argmax(data[:, 2])
print("Index pacienta:", idx)
print("Záznam:", data[idx])


[[129.6  78.2  93. ]
 [109.4  73.2  72. ]
 [136.3  92.2  61. ]
 [139.1  78.5  89. ]
 [ 95.7  75.7  80. ]
 [105.5  76.5  83. ]
 [126.9  85.3  58. ]
 [120.3  83.7  67. ]
 [124.7  84.1  86. ]
 [112.2  84.3  89. ]
 [138.2 101.4  72. ]
 [136.7  75.9  87. ]
 [126.   74.9  89. ]
 [141.9  71.9  70. ]
 [132.   86.2  91. ]
 [112.1  91.3  66. ]
 [130.5  78.9  64. ]
 [110.6  71.6  82. ]
 [138.2  71.8  81. ]
 [124.3  86.5  60. ]]
Priemer: [124.51   81.105  77.   ]
Smerodajná odchýlka: [12.72807527  7.73869983 11.28273017]
Počet pacientov s hypertenziou: 1
Priemerný systolický tlak: 141.9
Dáta s pulzným tlakom:
 [[129.6  78.2  93.   51.4]
 [109.4  73.2  72.   36.2]
 [136.3  92.2  61.   44.1]
 [139.1  78.5  89.   60.6]
 [ 95.7  75.7  80.   20. ]
 [105.5  76.5  83.   29. ]
 [126.9  85.3  58.   41.6]
 [120.3  83.7  67.   36.6]
 [124.7  84.1  86.   40.6]
 [112.2  84.3  89.   27.9]
 [138.2 101.4  72.   36.8]
 [136.7  75.9  87.   60.8]
 [126.   74.9  89.   51.1]
 [141.9  71.9  70.   70. ]
 [132.   86.2  9